name: Reusable Caller

on:
  push: 
  workflow_dispatch: 

jobs:
  checkov-scan:
    uses: emilioc7/devops-resources/.github/workflows/scan-checkov.yml@main
    with:
      checkov_version: "3.2.230"
      publicMessage: "This is a public message - NEW"
      super_token: $${{ vars.ADO_TOKEN }}
    secrets:
      secretMessage: ${{ secrets.SECRET_MESSAGE }}
